### ISSUE TITLE
Push 0.0.2 to PyPI

### ISSUE THREAD

**Issue by teamdoug** [casebeer/python-hkdf#3]
Hi Christopher,

I saw you bumped the version to 0.0.2 but that still does not appear to be on [PyPI](https://pypi.python.org/pypi/hkdf/). When will you be pushing that?

Thanks!
Doug

**Comment by casebeer** [comment]
Hi Doug, 

I just uploaded it. Sorry for the delay – I didn't have my PGP keys handy when I accepted your pull request. 

Thanks again, 

Chris
